### ISSUE TITLE
Next Link 2.4 not present after some calls

### ISSUE THREAD

**Issue by niksimms** [pazaan/decoding-contour-next-link#8] opened 2016-05-05 06:47 UTC
I was running the script using a crontab every 5 mins. This was all going well until the device would become unresponsive and could not be reached until I re-inserted the Next Link. I'm not sure if this Next link issue or the unit it is plugged into.
I am using a Odroid C with Ubuntu 14.

**Comment by niksimms** [comment] 2016-05-05 06:48
# Opening device
Traceback (most recent call last):
  File "/home/decoding-contour-next-link/read_minimed_next24.py", line 687, in <module>
    mt.initDevice()
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 234, in trigger
    if t.execute(event):
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 139, in execute
    machine.callback(getattr(event_data.model, func), event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 484, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/home/decoding-contour-next-link/read_minimed_next24.py", line 500, in openDevice
    self.device.open( self.USB_VID, self.USB_PID )
  File "hid.pyx", line 66, in hid.device.open (hid.c:1569)
IOError: open failed

**Comment by pazaan** [comment] 2016-05-05 08:23
I've seen this before. This can be related to #5, but there's also some extra code in the Android uploader that deals with message order differently, so I'll include that functionality as well.

**Comment by Ralph74** [comment] 2016-09-27 12:06
I am having the same problem on Pi.
I havn't quite got to cron job yet but I also notice that I loose the usb device. lsusb does not show Bayer. Even after pi reboot still no device until I unplug and re plug the Bayer meter into the USB. 
Android uploader is also very unreliable for me too and I wonder if it is cause by the same problem.
I really want to get the system working well on Pi so I can one bedside and one in school classroom.

**Comment by paulokow** [comment] 2017-08-26 17:00
I also hat this problem info Pi. I ported some code from chrome client and now it's not happening anymore. 
See my pull request #16

**Comment by paulokow** [comment] 2017-10-23 05:09
Fixed with PR #17

**Closed by paulokow** 2017-10-23 05:09 UTC
Labels: bug

**Comment by mortlind** [comment] 2017-10-23 05:39
I still have this issue on my RPi. I fear it is a power issue, and that it arises from the RPi USB port side after some reading activity concentrated over a longer duration. But this is just my hunch. I will try to add the CNL stick via a powered USB hub, and see if this issue does not arise after that.

**Comment by paulokow** [comment] 2017-10-23 09:06
Hi @mortlind, I did not face such issues till now on RPI. So if you do just feel free to re-open with some log file.
Before I was using a cron script (with root) to reset USB "just in case" the stick got stuck.

`
#!/bin/bash

service networking stop
sleep 2
echo 0 > /sys/devices/platform/soc/3f980000.usb/buspower
sleep 3
echo 1 > /sys/devices/platform/soc/3f980000.usb/buspower
sleep 2
service networking start
`

I will add it to the repo later.

**Comment by mortlind** [comment] 2017-10-23 11:35
@paulokow Yes, this works, but it also tears down my wireless interface which sits on the USB port. I think I can live with it, but it seems very drastical and it does not address the root cause.
